// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHjQG1fWO2VGrjV-MDqjYtHK0vXRULLng',
    appId: '1:168285576529:web:7f29581076e23a0ca04770',
    messagingSenderId: '168285576529',
    projectId: 'origo-ribhi',
    authDomain: 'origo-ribhi.firebaseapp.com',
    storageBucket: 'origo-ribhi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3SfuCFxSPLVFXlMxx5sG85V_1sNVCNc',
    appId: '1:168285576529:android:fc544d3336175850a04770',
    messagingSenderId: '168285576529',
    projectId: 'origo-ribhi',
    storageBucket: 'origo-ribhi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHh5xGr_bOAcIC5e-7Ve66HK7TzBTjpo',
    appId: '1:168285576529:ios:a3b7b96a77e7f5e6a04770',
    messagingSenderId: '168285576529',
    projectId: 'origo-ribhi',
    storageBucket: 'origo-ribhi.firebasestorage.app',
    iosBundleId: 'com.example.ribhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHh5xGr_bOAcIC5e-7Ve66HK7TzBTjpo',
    appId: '1:168285576529:ios:a3b7b96a77e7f5e6a04770',
    messagingSenderId: '168285576529',
    projectId: 'origo-ribhi',
    storageBucket: 'origo-ribhi.firebasestorage.app',
    iosBundleId: 'com.example.ribhi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHjQG1fWO2VGrjV-MDqjYtHK0vXRULLng',
    appId: '1:168285576529:web:79f2d95b91344be0a04770',
    messagingSenderId: '168285576529',
    projectId: 'origo-ribhi',
    authDomain: 'origo-ribhi.firebaseapp.com',
    storageBucket: 'origo-ribhi.firebasestorage.app',
  );
}
